{"name": "En tant que user je veux connecter au site", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00E31ED3+2236115]\n\tOrdinal0 [0x00DC92F1+1807089]\n\tOrdinal0 [0x00CD65C0+812480]\n\tOrdinal0 [0x00D06586+1009030]\n\tOrdinal0 [0x00CFC416+967702]\n\tOrdinal0 [0x00D21A8C+1120908]\n\tOrdinal0 [0x00CFBD84+966020]\n\tOrdinal0 [0x00D21CA4+1121444]\n\tOrdinal0 [0x00D359E2+1202658]\n\tOrdinal0 [0x00D218A6+1120422]\n\tOrdinal0 [0x00CFA73D+960317]\n\tOrdinal0 [0x00CFB71F+964383]\n\tGetHandleVerifier [0x010DE7E2+2743074]\n\tGetHandleVerifier [0x010D08D4+2685972]\n\tGetHandleVerifier [0x00EC2BAA+532202]\n\tGetHandleVerifier [0x00EC1990+527568]\n\tOrdinal0 [0x00DD080C+1837068]\n\tOrdinal0 [0x00DD4CD8+1854680]\n\tOrdinal0 [0x00DD4DC5+1854917]\n\tOrdinal0 [0x00DDED64+1895780]\n\tBaseThreadInitThunk [0x77176739+25]\n\tRtlGetFullPathName_UEx [0x77AA8FD2+1218]\n\tRtlGetFullPathName_UEx [0x77AA8F9D+1165]\n\n", "trace": "  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Features\\steps\\SignUp_Steps.py\", line 26, in OpenPopupLogin\n    context.driver.find_element(By.XPATH, \"/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/section[1]/div[1]/div[3]/div[\"\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 88, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 396, in _execute\n    return self._parent.execute(command, params)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch chrome browser", "status": "passed", "start": 1667585587567, "stop": 1667585588665}, {"name": "When le site est lancé", "status": "passed", "start": 1667585588665, "stop": 1667585611454}, {"name": "Then Ouvrir le popup de connexion", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00E31ED3+2236115]\n\tOrdinal0 [0x00DC92F1+1807089]\n\tOrdinal0 [0x00CD65C0+812480]\n\tOrdinal0 [0x00D06586+1009030]\n\tOrdinal0 [0x00CFC416+967702]\n\tOrdinal0 [0x00D21A8C+1120908]\n\tOrdinal0 [0x00CFBD84+966020]\n\tOrdinal0 [0x00D21CA4+1121444]\n\tOrdinal0 [0x00D359E2+1202658]\n\tOrdinal0 [0x00D218A6+1120422]\n\tOrdinal0 [0x00CFA73D+960317]\n\tOrdinal0 [0x00CFB71F+964383]\n\tGetHandleVerifier [0x010DE7E2+2743074]\n\tGetHandleVerifier [0x010D08D4+2685972]\n\tGetHandleVerifier [0x00EC2BAA+532202]\n\tGetHandleVerifier [0x00EC1990+527568]\n\tOrdinal0 [0x00DD080C+1837068]\n\tOrdinal0 [0x00DD4CD8+1854680]\n\tOrdinal0 [0x00DD4DC5+1854917]\n\tOrdinal0 [0x00DDED64+1895780]\n\tBaseThreadInitThunk [0x77176739+25]\n\tRtlGetFullPathName_UEx [0x77AA8FD2+1218]\n\tRtlGetFullPathName_UEx [0x77AA8F9D+1165]\n\n", "trace": "  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Features\\steps\\SignUp_Steps.py\", line 26, in OpenPopupLogin\n    context.driver.find_element(By.XPATH, \"/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/section[1]/div[1]/div[3]/div[\"\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 88, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 396, in _execute\n    return self._parent.execute(command, params)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667585611454, "stop": 1667585611488}, {"name": "And Remplir les champs avec un email \"Email\" et un mot de passe \"Password\"", "status": "skipped", "start": 1667585611489, "stop": 1667585611489}, {"name": "Then Clicker sur le boutton Se connecter", "status": "skipped", "start": 1667585611489, "stop": 1667585611489}, {"name": "Then User est connecté avec succès", "status": "skipped", "start": 1667585611489, "stop": 1667585611489}, {"name": "And Fermer le browser", "status": "skipped", "start": 1667585611489, "stop": 1667585611489}], "start": 1667585587567, "stop": 1667585611489, "uuid": "ba02a4a1-d0b2-4823-ba98-85236ef1ced2", "historyId": "5c5515c05a466413c618bb63d6f9334b", "fullName": "AA User i want to sign up: En tant que user je veux connecter au site", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "AA User i want to sign up"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}